/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LasRouteImport } from './routes/las'
import { Route as AppsDesignsystemIndexRouteImport } from './routes/apps/designsystem/index'
import { Route as AppsHelloIndexRouteImport } from './routes/apps/hello/index'
import { Route as AppsValvIndexRouteImport } from './routes/apps/valv/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LasRoute = LasRouteImport.update({
  id: '/las',
  path: '/las',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsDesignsystemIndexRoute = AppsDesignsystemIndexRouteImport.update({
  id: '/apps/designsystem/',
  path: '/apps/designsystem/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsHelloIndexRoute = AppsHelloIndexRouteImport.update({
  id: '/apps/hello/',
  path: '/apps/hello/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsValvIndexRoute = AppsValvIndexRouteImport.update({
  id: '/apps/valv/',
  path: '/apps/valv/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/las': typeof LasRoute
  '/apps/designsystem/': typeof AppsDesignsystemIndexRoute
  '/apps/hello/': typeof AppsHelloIndexRoute
  '/apps/valv/': typeof AppsValvIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/las': typeof LasRoute
  '/apps/designsystem': typeof AppsDesignsystemIndexRoute
  '/apps/hello': typeof AppsHelloIndexRoute
  '/apps/valv': typeof AppsValvIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/las': typeof LasRoute
  '/apps/designsystem/': typeof AppsDesignsystemIndexRoute
  '/apps/hello/': typeof AppsHelloIndexRoute
  '/apps/valv/': typeof AppsValvIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/las' | '/apps/designsystem/' | '/apps/hello/' | '/apps/valv/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/las' | '/apps/designsystem' | '/apps/hello' | '/apps/valv'
  id:
    | '__root__'
    | '/'
    | '/las'
    | '/apps/designsystem/'
    | '/apps/hello/'
    | '/apps/valv/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LasRoute: typeof LasRoute
  AppsDesignsystemIndexRoute: typeof AppsDesignsystemIndexRoute
  AppsHelloIndexRoute: typeof AppsHelloIndexRoute
  AppsValvIndexRoute: typeof AppsValvIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/las': {
      id: '/las'
      path: '/las'
      fullPath: '/las'
      preLoaderRoute: typeof LasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/designsystem/': {
      id: '/apps/designsystem/'
      path: '/apps/designsystem'
      fullPath: '/apps/designsystem/'
      preLoaderRoute: typeof AppsDesignsystemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/hello/': {
      id: '/apps/hello/'
      path: '/apps/hello'
      fullPath: '/apps/hello/'
      preLoaderRoute: typeof AppsHelloIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/valv/': {
      id: '/apps/valv/'
      path: '/apps/valv'
      fullPath: '/apps/valv/'
      preLoaderRoute: typeof AppsValvIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LasRoute: LasRoute,
  AppsDesignsystemIndexRoute: AppsDesignsystemIndexRoute,
  AppsHelloIndexRoute: AppsHelloIndexRoute,
  AppsValvIndexRoute: AppsValvIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
